@startuml
'https://plantuml.com/sequence-diagram

autonumber

== Authentication (login/refresh) ==
  Client -> JavalinServer: POST /auth/login
  JavalinServer -> Auth: login(ctx)
  Auth -> Auth: validate credentials
  Auth --> Client: JWT / session token

@enduml